### ISSUE TITLE
2110 SDP violates the RFC

### ISSUE THREAD

**Issue by kierank** [SMPTE/st2110-10#5]
See https://github.com/AMWA-TV/sdpoker/pull/12

**Comment by tkernen** [comment]
Issue reassigned to rp2110-23 repo
https://github.com/SMPTE/rp2110-23/issues/1

**Comment by tkernen** [comment]
Closed and reassigned to rp2110-23 repo
https://github.com/SMPTE/rp2110-23/issues/1

**Comment by tkernen** [comment]
Closed and reassigned to rp2110-23 repo
https://github.com/SMPTE/rp2110-23/issues/1
